{
 "title": "Sei SLO",
 "tags": [ "SLO" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "validator_component", "label": "Validator component label", "query": "validators" },
   {
    "name": "webapp_component",
    "label": "Validator metadata component label",
    "query": "webapp"
   },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_latest_block_height, chain_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Raw Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tendermint_consensus_latest_block_height{chain_id=~\"$chain_id\"})",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "title": "Block Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(tendermint_consensus_block_interval_seconds_bucket{chain_id=~\"$chain_id\"}[5m])) by (le)) ",
     "legendFormat": "p50 block time"
    },
    {
     "expr": "min(blocks_per_second{chain_id=~\"$chain_id\", component=\"$validator_component\"})",
     "legendFormat": "Blocks Per Second"
    }
   ]
  },
  {
   "title": "Throughput Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "max(rate(sei_cosmos_throughput_transaction_count{chain_id=~\"$chain_id\", component=\"$validator_component\", mode=\"deliver\"}[5m]))",
     "legendFormat": "Transactions per sec"
    },
    {
     "expr": "max(rate(sei_cosmos_throughput_message_count{chain_id=~\"$chain_id\", component=\"$validator_component\"}[5m]))",
     "legendFormat": "Messages Per Sec"
    }
   ]
  },
  { "title": "Chain Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Chain Performance SLO ",
   "type": "bargauge",
   "description": "1.0 = 100% of blocks are produced within 1 second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo_consensus_block_speed_5m{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "5 mins"
    },
    {
     "expr": "slo_consensus_block_speed_30m{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "30 mins"
    },
    {
     "expr": "slo_consensus_block_speed_1h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "1 hour"
    },
    {
     "expr": "slo_consensus_block_speed_6h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "6 hours"
    },
    {
     "expr": "slo_consensus_block_speed_12h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "12 hours"
    },
    {
     "expr": "slo_consensus_block_speed_24h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "24 hours"
    },
    {
     "expr": "slo_consensus_block_speed_7d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "7 days"
    },
    {
     "expr": "slo_consensus_block_speed_14d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "14 days"
    },
    {
     "expr": "slo_consensus_block_speed_30d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "30 days"
    }
   ]
  },
  {
   "title": "Chain Uptime SLO ",
   "type": "bargauge",
   "description": "1.0 = 100% of the time interval is producing at least 1 block per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo_blocks_per_second_5m{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "5 mins"
    },
    {
     "expr": "slo_blocks_per_second_30m{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "30 mins"
    },
    {
     "expr": "slo_blocks_per_second_1h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "1 hour"
    },
    {
     "expr": "slo_blocks_per_second_6h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "6 hours"
    },
    {
     "expr": "slo_blocks_per_second_12h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "12 hours"
    },
    {
     "expr": "slo_blocks_per_second_24h{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "24 hours"
    },
    {
     "expr": "slo_blocks_per_second_7d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "7 days"
    },
    {
     "expr": "slo_blocks_per_second_14d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "14 days"
    },
    {
     "expr": "slo_blocks_per_second_30d{chain_id=~\"$chain_id\", component=\"$validator_component\"}",
     "legendFormat": "30 days"
    }
   ]
  },
  { "title": "Raw Metrics (Validator)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Validator Performance ",
   "type": "timeseries",
   "description": "Raw metrics for validator proposal latency (in seconds)\n\nTendermint Metric:\ntendermint_consensus_propose_latency_bucket\n\nrecord:validator_propose_latency\nexpr:max by (chain_id, moniker, pubkey_hash) (cosmos_validators_active{component=\"$validator_component\"} > 0) * 0 + on (chain_id, pubkey_hash) group_left () max by (pubkey_hash, chain_id) (histogram_quantile(0.75, label_replace(tendermint_consensus_propose_latency_bucket{component=\"$validator_component\"}, \"pubkey_hash\", \"$1\", \"proposer_address\", \"(.+)\")))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (moniker, pubkey_hash) (validator_propose_latency)",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validator Block Misses",
   "type": "timeseries",
   "description": "> 95% to get jailed\n\n\nrecord:block_miss_percentage_sliding_window\nexpr:max by (moniker, chain_id, address) (cosmos_validators_missed_blocks{component=\"$validator_component\"}) / ignoring (moniker, address) group_left () max by (chain_id) (cosmos_params_signed_blocks_window{component=\"$validator_component\"})\nCosmos Level Metrics:\ncosmos_validators_missed_blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (moniker, address) (block_miss_percentage_sliding_window)",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validators Jailed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (moniker) (cosmos_validators_jailed{component=\"$webapp_component\"}) > 0",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  { "title": "Validator Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Validator Performance SLO",
   "type": "table",
   "description": "1.0 = 100% of the time the validator sent in proposals under 500ms",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (moniker) (slo_validator_proposal_latency_1h{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (moniker) (slo_validator_proposal_latency_24h{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (moniker) (slo_validator_proposal_latency_7d{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Uptime SLO",
   "type": "table",
   "description": "1.0 = 100% of the time the validator is missing more than 70% of the blocks in the time period",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (moniker) (slo_block_miss_1h{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (moniker) (slo_block_miss_24h{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (moniker) (slo_block_miss_7d{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}